Repository META-INT6/REPLANET_React_V2, pull requests merged in 2023-11, with the labels that each got.

#2 [Feature] 서포트 봇 0.1.5
  package-lock.json
  package.json
  src/assets/css/supportbot.css
  src/component/charts/CategoryCampaign.js
  src/component/modals/ModalSupportbot.js
  src/component/supportbots/items/responseitem/FifthResBubble.js
  src/component/supportbots/items/responseitem/FirstResBubble.js
  src/component/supportbots/items/responseitem/FourthResBubble.js
  src/component/supportbots/items/responseitem/SecondResBubble.js
  src/component/supportbots/items/responseitem/ThirdResBubble.js
  src/component/supportbots/items/textitem/AnyQuestion.js
  src/component/supportbots/list/BubbleList.js
Labels: supportbot

#6 [Feature] ORG 정보 수정 0.1.1
  src/App.js
  src/apis/PointAPI.js
  src/assets/css/common.css
  src/modules/PointModule.js
  src/pages/EditOrg.js
  src/pages/EditPwdConfirm.js
Labels: organization

#10 [Feature] ORG 정보 수정0.2.1
  package-lock.json
  public/exchangeFiles/54e265ec3f94416a9784d3bb19dea73d.jpg
  public/exchangeFiles/acc7eac7c4474bca8a0072d1fa128872.jpg
  public/orgImgs/0351065380cc4e5fbdb06ab86e9b0f53.jpg
  public/orgImgs/141c52af93064365a283325bc8bbab6a.jpeg
  public/orgImgs/1d426914d6f64b6e8d5e567f87737c7d.jpeg
  public/orgImgs/3401ebdf434a4a2b9550499b8be61375.png
  public/orgImgs/56994b12259e4de085406c8608765fd5.jpg
  public/orgImgs/88e7c91919924d49b9db16303bb49f82.jpg
  src/App.js
  src/apis/OrgAPI.js
  src/apis/PointAPI.js
  src/assets/css/mypage.css
  src/modules/OrgModule.js
  src/modules/PointModule.js
  src/modules/index.js
  src/pages/EditOrg.js
  src/pages/EditPwdConfirm.js
  src/pages/org/EditPwdConfirm.js
  src/pages/org/MyPageOrg.js
  src/pages/org/OrgEdit.js
  src/pages/org/OrgWithdraw.js
  src/pages/points/ExchangePoint.js
  src/pages/users/MyPage.js
  src/pages/users/Receipt.js
Labels: organization

#8 [FEATURE] 리뷰 사용자 추가 리팩토링
  public/reviewImgs/17649af9-f1b0-4991-8552-2277d2608471.png
  public/reviewImgs/21a480c6-2f99-4780-9c2b-b9db306755fd.jpg
  public/reviewImgs/42a54d76-2809-4a45-83cd-1dc0fee48e09.png
  public/reviewImgs/43a91b399908479ab0548cfae4b246da.jpg
  public/reviewImgs/44d2990f-e8f7-4d69-8984-bb16540da10f.png
  public/reviewImgs/49dae685-54a8-49fd-937d-e289717f851f.png
  public/reviewImgs/4aa41a84-b67e-4429-94e8-6206bfbb23c1.jpg
  public/reviewImgs/82f723b6-199e-401c-8515-a497465bc5f9.jpg
  public/reviewImgs/9676b4b0794d4098b105b410bde430b9.jpeg
  public/reviewImgs/caf5570b-8586-47b6-bb1b-fd24aada988f.jpg
  src/App.js
  src/apis/ReviewAPI.js
  src/assets/css/common.css
  src/component/campaigns/items/CampaignItem.js
  src/component/reviews/items/Review.js
  src/component/reviews/items/ReviewComment.js
  src/component/reviews/items/ReviewListSearchbar.js
  src/component/reviews/lists/ReviewList.js
  src/modules/ReviewModule.js
  src/pages/org/MyPageOrg.js
  src/pages/reviews/Reviews.js
Labels: review

#11 [FEATURE] 기부처 목록 조회 0.1.1
  public/campaigns/791f7cd93c5a4f1d86974c2cb00aa528.jfif
  public/campaigns/b3d29c9311764071a879168c33a5293e.png
  src/apis/BookmarkAPI.js
  src/apis/CampaignListAPI.js
  src/component/campaigns/items/CampaignContent.js
  src/component/campaigns/items/CampaignItem.js
  src/component/campaigns/items/CampaignPicture.js
  src/component/campaigns/items/CampaignPlan.js
  src/component/campaigns/items/CampaignSidebar.js
  src/component/campaigns/items/CountBox.js
  src/component/campaigns/items/Participation.js
  src/component/campaigns/lists/CampaignList.js
  src/component/campaigns/lists/ParticipationDetails.js
  src/component/org/lists/OrgCamList.js
  src/modules/CampaignModule.js
  src/pages/campaigns/CampaignDetails.js
  src/pages/campaigns/CampaignModify.js
  src/pages/campaigns/CampaignRegist.js
Labels: organization

#15 [FEATURE] 기부처 상세페이지 조회 0.1.2
  package-lock.json
  package.json
  public/campaigns/0ab4586dcbfe403a9850596b7e50a7a8.jfif
  public/campaigns/0cfc0f2d15aa43faa5fb94acccd4cebf.jfif
  public/campaigns/1298711670514cc2944b9651a302e7fa.jfif
  public/campaigns/175f71d28ae7494ca8455cc2181aa723.jfif
  public/campaigns/20609bf3cd344ae8ac7139955263c41b.jfif
  public/campaigns/5647705c305f41e895cd711e9ed72588.jfif
  public/campaigns/5f27b45577fc49e49be67bad4be61286.jfif
  public/campaigns/60b6d14b57c049b79ac9380debe47973.jfif
  public/campaigns/76ba2a576bb146c4a351ec9ccbaf2254.jfif
  public/campaigns/791f7cd93c5a4f1d86974c2cb00aa528.jfif
  public/campaigns/7e28084c924a4998927014198121f609.png
  public/campaigns/800fbeecfc7c4e72af0b4dfa3ce0443c.jfif
  public/campaigns/9766cbfe6d294aee82845ad2903957da.jfif
  public/campaigns/9f625ba1603648e79424ed553f86889d.jfif
  public/campaigns/ac0db01ba5804283b4569bcbeddf2005.jfif
  public/campaigns/b34646e591664175b392ca9878ceb716.jfif
  public/campaigns/c0239ecd2c874eaebbed759dc99e2430.jfif
  public/campaigns/d7ec58d6cf714fe8971dcfcf8f9259fb.jfif
  public/campaigns/de44b83031cd47c5a2b1bc831a653dd6.jfif
  public/campaigns/dea0630c4c544cb98b7f4058b49e98ef.jfif
  public/campaigns/default/topButton.png
  public/campaigns/e32cc90cce7544c594989890409723f2.jfif
  public/campaigns/f9897a2b0ab3485ab33a5cb279b31795.jfif
  public/orgImgs/441eb4f2bbd34d0ca83c13642ae2fa87.png
  public/orgImgs/b4fa1ef6ba4345329a3089902db66482.jpg
  src/apis/CampaignListAPI.js
  src/apis/DonationAPI.js
  src/assets/css/campaign.css
  src/assets/css/supportbot.css
  src/component/campaigns/items/CampaignContent.js
  src/component/campaigns/items/CampaignItem.js
  src/component/campaigns/items/CampaignPlan.js
  src/component/campaigns/items/CampaignSidebar.js
  src/component/campaigns/items/GotoTopButton.js
  src/component/campaigns/items/Participation.js
  src/component/campaigns/lists/CampaignList.js
  src/component/campaigns/lists/ParticipationDetails.js
  src/component/mypage/items/HeartButton.js
  src/component/org/lists/OrgCamList.js
  src/modules/CampaignModule.js
  src/pages/campaigns/CampaignDetails.js
  src/pages/campaigns/CampaignModify.js
  src/pages/campaigns/CampaignRegist.js
  src/pages/org/MyPageOrg.js
Labels: organization

#16 [REFACTOR] 텍스트 에디터 큰 용량 이미지 핸들링 & 전체적으로 코드 리팩토링 중
  package-lock.json
  package.json
  public/reviewImgs/11b4d955-4e15-470d-a63d-8ce801d08608.png
  public/reviewImgs/1769260c-aad5-4e47-9bb0-467e9d9c8a45.png
  public/reviewImgs/3237b30f-8774-4873-9272-61d6eb293216.png
  public/reviewImgs/375f679e-e9cf-453f-9983-cf0f99e60397.png
  public/reviewImgs/3908b040-fa85-448e-9ea2-4e69ac779d7c.png
  public/reviewImgs/3dd26be7-faf8-4723-803e-b8a138bd7097.png
  public/reviewImgs/402a142f-228e-42e6-a364-3e0500f1e4dc.png
  public/reviewImgs/5aabd31f-b2d1-4e63-be18-36387e0afa62.png
  public/reviewImgs/851980db-8e96-4ec0-aeae-8369d39313d1.png
  public/reviewImgs/853ffdef69ce4b8a8b7a1433e956e681.jpeg
  public/reviewImgs/add0852c-0a9b-4c1c-bab7-4756fdddd420.png
  public/reviewImgs/bc5e5b6a-69f6-457c-afd4-f16383da48b0.png
  public/reviewImgs/c5fa67553aa942d0860f021727965d24.jpg
  public/reviewImgs/c7b9fa34d34d42f4b2605ee8ac7c1187.jpeg
  public/reviewImgs/ccf07159-2149-4d04-961f-6fc71fbe16d8.png
  public/reviewImgs/e9248d22-fe85-46fc-ab91-92a325a920f0.png
  public/reviewImgs/efa765dc-c042-46b9-be0f-39cfa52e4200.png
  public/reviewImgs/f72adad2-afc5-4a65-98a2-1c848b34f60f.png
  public/reviewImgs/fec426ca-4d4e-4a60-9f78-9cbddc749fa6.png
  src/component/reviews/items/Review.js
  src/component/reviews/items/ReviewComment.js
  src/component/reviews/items/ReviewDetailsIntroductionBox.js
  src/component/reviews/items/TextEditor.js
  src/pages/auth/Login.js
  src/pages/reviews/ReviewModify.js
Labels: review

#14 [Feature] 통계 조회 0.2.2
  src/component/campaigns/lists/CampaignList.js
  src/component/charts/CategoryCampaign.js
  src/component/charts/HistoryChart.js
Labels: chart
